//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.16 at 01:00:50 PM BRT 
//

package br.com.glosma.associacao.faturas.hospital.santahelena;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="prestadorParaOperadora">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="loteGuias">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="numeroLote" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="guiasTISS">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="guiaResumoInternacao" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="numeroGuiaPrestador" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                                 &lt;element name="numeroGuiaSolicitacaoInternacao" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                                 &lt;element name="numeroGuiaOperadora" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                                 &lt;element name="senha" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                                 &lt;element name="dadosBeneficiario">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="numeroCarteira" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                           &lt;element name="atendimentoRN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="nomeBeneficiario" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                                 &lt;element name="procedimentosExecutados">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="procedimentoExecutado" maxOccurs="unbounded" minOccurs="0">
 *                                                             &lt;complexType>
 *                                                               &lt;complexContent>
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                                   &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                                                                     &lt;element name="dataExecucao" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                                                                     &lt;element name="horaInicial" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *                                                                     &lt;element name="horaFinal" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *                                                                     &lt;element name="codigoTabela" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                                     &lt;element name="codigoProcedimento" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                                     &lt;element name="descricaoProcedimento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                                     &lt;element name="quantidadeExecutada" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                                     &lt;element name="reducaoAcrescimo" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                                     &lt;element name="valorUnitario" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                                     &lt;element name="valorTotal" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                                     &lt;element name="unidadeMedida" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                                   &lt;/choice>
 *                                                                 &lt;/restriction>
 *                                                               &lt;/complexContent>
 *                                                             &lt;/complexType>
 *                                                           &lt;/element>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                                 &lt;element name="valorTotal">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="valorProcedimentos" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                           &lt;element name="valorDiarias" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                           &lt;element name="valorTaxasAlugueis" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                           &lt;element name="valorMateriais" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                           &lt;element name="valorMedicamentos" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                           &lt;element name="valorOPME" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                           &lt;element name="valorGasesMedicinais" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                           &lt;element name="valorTotalGeral" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "prestadorParaOperadora" })
@XmlRootElement(name = "mensagemTISS")
public class ContainerDadosSantaHelenaXML {

	@XmlElement(required = true)
	protected ContainerDadosSantaHelenaXML.PrestadorParaOperadora prestadorParaOperadora;

	/**
	 * Gets the value of the prestadorParaOperadora property.
	 * 
	 * @return possible object is {@link ContainerDadosSantaHelenaXML.PrestadorParaOperadora }
	 * 
	 */
	public ContainerDadosSantaHelenaXML.PrestadorParaOperadora getPrestadorParaOperadora() {
		return prestadorParaOperadora;
	}

	/**
	 * Sets the value of the prestadorParaOperadora property.
	 * 
	 * @param value
	 *            allowed object is {@link ContainerDadosSantaHelenaXML.PrestadorParaOperadora }
	 * 
	 */
	public void setPrestadorParaOperadora(
			ContainerDadosSantaHelenaXML.PrestadorParaOperadora value) {
		this.prestadorParaOperadora = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="loteGuias">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="numeroLote" type="{http://www.w3.org/2001/XMLSchema}short"/>
	 *                   &lt;element name="guiasTISS">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="guiaResumoInternacao" maxOccurs="unbounded" minOccurs="0">
	 *                               &lt;complexType>
	 *                                 &lt;complexContent>
	 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                     &lt;sequence>
	 *                                       &lt;element name="numeroGuiaPrestador" type="{http://www.w3.org/2001/XMLSchema}long"/>
	 *                                       &lt;element name="numeroGuiaSolicitacaoInternacao" type="{http://www.w3.org/2001/XMLSchema}long"/>
	 *                                       &lt;element name="numeroGuiaOperadora" type="{http://www.w3.org/2001/XMLSchema}long"/>
	 *                                       &lt;element name="senha" type="{http://www.w3.org/2001/XMLSchema}long"/>
	 *                                       &lt;element name="dadosBeneficiario">
	 *                                         &lt;complexType>
	 *                                           &lt;complexContent>
	 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                               &lt;sequence>
	 *                                                 &lt;element name="numeroCarteira" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                                                 &lt;element name="atendimentoRN" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                                 &lt;element name="nomeBeneficiario" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                               &lt;/sequence>
	 *                                             &lt;/restriction>
	 *                                           &lt;/complexContent>
	 *                                         &lt;/complexType>
	 *                                       &lt;/element>
	 *                                       &lt;element name="procedimentosExecutados">
	 *                                         &lt;complexType>
	 *                                           &lt;complexContent>
	 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                               &lt;sequence>
	 *                                                 &lt;element name="procedimentoExecutado" maxOccurs="unbounded" minOccurs="0">
	 *                                                   &lt;complexType>
	 *                                                     &lt;complexContent>
	 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                                         &lt;choice maxOccurs="unbounded" minOccurs="0">
	 *                                                           &lt;element name="dataExecucao" type="{http://www.w3.org/2001/XMLSchema}date"/>
	 *                                                           &lt;element name="horaInicial" type="{http://www.w3.org/2001/XMLSchema}time"/>
	 *                                                           &lt;element name="horaFinal" type="{http://www.w3.org/2001/XMLSchema}time"/>
	 *                                                           &lt;element name="codigoTabela" type="{http://www.w3.org/2001/XMLSchema}byte"/>
	 *                                                           &lt;element name="codigoProcedimento" type="{http://www.w3.org/2001/XMLSchema}int"/>
	 *                                                           &lt;element name="descricaoProcedimento" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                                           &lt;element name="quantidadeExecutada" type="{http://www.w3.org/2001/XMLSchema}byte"/>
	 *                                                           &lt;element name="reducaoAcrescimo" type="{http://www.w3.org/2001/XMLSchema}float"/>
	 *                                                           &lt;element name="valorUnitario" type="{http://www.w3.org/2001/XMLSchema}float"/>
	 *                                                           &lt;element name="valorTotal" type="{http://www.w3.org/2001/XMLSchema}float"/>
	 *                                                           &lt;element name="unidadeMedida" type="{http://www.w3.org/2001/XMLSchema}byte"/>
	 *                                                         &lt;/choice>
	 *                                                       &lt;/restriction>
	 *                                                     &lt;/complexContent>
	 *                                                   &lt;/complexType>
	 *                                                 &lt;/element>
	 *                                               &lt;/sequence>
	 *                                             &lt;/restriction>
	 *                                           &lt;/complexContent>
	 *                                         &lt;/complexType>
	 *                                       &lt;/element>
	 *                                       &lt;element name="valorTotal">
	 *                                         &lt;complexType>
	 *                                           &lt;complexContent>
	 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                               &lt;sequence>
	 *                                                 &lt;element name="valorProcedimentos" type="{http://www.w3.org/2001/XMLSchema}float"/>
	 *                                                 &lt;element name="valorDiarias" type="{http://www.w3.org/2001/XMLSchema}float"/>
	 *                                                 &lt;element name="valorTaxasAlugueis" type="{http://www.w3.org/2001/XMLSchema}float"/>
	 *                                                 &lt;element name="valorMateriais" type="{http://www.w3.org/2001/XMLSchema}float"/>
	 *                                                 &lt;element name="valorMedicamentos" type="{http://www.w3.org/2001/XMLSchema}float"/>
	 *                                                 &lt;element name="valorOPME" type="{http://www.w3.org/2001/XMLSchema}float"/>
	 *                                                 &lt;element name="valorGasesMedicinais" type="{http://www.w3.org/2001/XMLSchema}float"/>
	 *                                                 &lt;element name="valorTotalGeral" type="{http://www.w3.org/2001/XMLSchema}float"/>
	 *                                               &lt;/sequence>
	 *                                             &lt;/restriction>
	 *                                           &lt;/complexContent>
	 *                                         &lt;/complexType>
	 *                                       &lt;/element>
	 *                                     &lt;/sequence>
	 *                                   &lt;/restriction>
	 *                                 &lt;/complexContent>
	 *                               &lt;/complexType>
	 *                             &lt;/element>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "loteGuias" })
	public static class PrestadorParaOperadora {

		@XmlElement(required = true)
		protected ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias loteGuias;

		/**
		 * Gets the value of the loteGuias property.
		 * 
		 * @return possible object is
		 *         {@link ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias }
		 * 
		 */
		public ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias getLoteGuias() {
			return loteGuias;
		}

		/**
		 * Sets the value of the loteGuias property.
		 * 
		 * @param value
		 *            allowed object is
		 *            {@link ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias }
		 * 
		 */
		public void setLoteGuias(
				ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias value) {
			this.loteGuias = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="numeroLote" type="{http://www.w3.org/2001/XMLSchema}short"/>
		 *         &lt;element name="guiasTISS">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="guiaResumoInternacao" maxOccurs="unbounded" minOccurs="0">
		 *                     &lt;complexType>
		 *                       &lt;complexContent>
		 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                           &lt;sequence>
		 *                             &lt;element name="numeroGuiaPrestador" type="{http://www.w3.org/2001/XMLSchema}long"/>
		 *                             &lt;element name="numeroGuiaSolicitacaoInternacao" type="{http://www.w3.org/2001/XMLSchema}long"/>
		 *                             &lt;element name="numeroGuiaOperadora" type="{http://www.w3.org/2001/XMLSchema}long"/>
		 *                             &lt;element name="senha" type="{http://www.w3.org/2001/XMLSchema}long"/>
		 *                             &lt;element name="dadosBeneficiario">
		 *                               &lt;complexType>
		 *                                 &lt;complexContent>
		 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                                     &lt;sequence>
		 *                                       &lt;element name="numeroCarteira" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *                                       &lt;element name="atendimentoRN" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                                       &lt;element name="nomeBeneficiario" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                                     &lt;/sequence>
		 *                                   &lt;/restriction>
		 *                                 &lt;/complexContent>
		 *                               &lt;/complexType>
		 *                             &lt;/element>
		 *                             &lt;element name="procedimentosExecutados">
		 *                               &lt;complexType>
		 *                                 &lt;complexContent>
		 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                                     &lt;sequence>
		 *                                       &lt;element name="procedimentoExecutado" maxOccurs="unbounded" minOccurs="0">
		 *                                         &lt;complexType>
		 *                                           &lt;complexContent>
		 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                                               &lt;choice maxOccurs="unbounded" minOccurs="0">
		 *                                                 &lt;element name="dataExecucao" type="{http://www.w3.org/2001/XMLSchema}date"/>
		 *                                                 &lt;element name="horaInicial" type="{http://www.w3.org/2001/XMLSchema}time"/>
		 *                                                 &lt;element name="horaFinal" type="{http://www.w3.org/2001/XMLSchema}time"/>
		 *                                                 &lt;element name="codigoTabela" type="{http://www.w3.org/2001/XMLSchema}byte"/>
		 *                                                 &lt;element name="codigoProcedimento" type="{http://www.w3.org/2001/XMLSchema}int"/>
		 *                                                 &lt;element name="descricaoProcedimento" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                                                 &lt;element name="quantidadeExecutada" type="{http://www.w3.org/2001/XMLSchema}byte"/>
		 *                                                 &lt;element name="reducaoAcrescimo" type="{http://www.w3.org/2001/XMLSchema}float"/>
		 *                                                 &lt;element name="valorUnitario" type="{http://www.w3.org/2001/XMLSchema}float"/>
		 *                                                 &lt;element name="valorTotal" type="{http://www.w3.org/2001/XMLSchema}float"/>
		 *                                                 &lt;element name="unidadeMedida" type="{http://www.w3.org/2001/XMLSchema}byte"/>
		 *                                               &lt;/choice>
		 *                                             &lt;/restriction>
		 *                                           &lt;/complexContent>
		 *                                         &lt;/complexType>
		 *                                       &lt;/element>
		 *                                     &lt;/sequence>
		 *                                   &lt;/restriction>
		 *                                 &lt;/complexContent>
		 *                               &lt;/complexType>
		 *                             &lt;/element>
		 *                             &lt;element name="valorTotal">
		 *                               &lt;complexType>
		 *                                 &lt;complexContent>
		 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                                     &lt;sequence>
		 *                                       &lt;element name="valorProcedimentos" type="{http://www.w3.org/2001/XMLSchema}float"/>
		 *                                       &lt;element name="valorDiarias" type="{http://www.w3.org/2001/XMLSchema}float"/>
		 *                                       &lt;element name="valorTaxasAlugueis" type="{http://www.w3.org/2001/XMLSchema}float"/>
		 *                                       &lt;element name="valorMateriais" type="{http://www.w3.org/2001/XMLSchema}float"/>
		 *                                       &lt;element name="valorMedicamentos" type="{http://www.w3.org/2001/XMLSchema}float"/>
		 *                                       &lt;element name="valorOPME" type="{http://www.w3.org/2001/XMLSchema}float"/>
		 *                                       &lt;element name="valorGasesMedicinais" type="{http://www.w3.org/2001/XMLSchema}float"/>
		 *                                       &lt;element name="valorTotalGeral" type="{http://www.w3.org/2001/XMLSchema}float"/>
		 *                                     &lt;/sequence>
		 *                                   &lt;/restriction>
		 *                                 &lt;/complexContent>
		 *                               &lt;/complexType>
		 *                             &lt;/element>
		 *                           &lt;/sequence>
		 *                         &lt;/restriction>
		 *                       &lt;/complexContent>
		 *                     &lt;/complexType>
		 *                   &lt;/element>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "numeroLote", "guiasTISS" })
		public static class LoteGuias {

			protected short numeroLote;
			@XmlElement(required = true)
			protected ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS guiasTISS;

			/**
			 * Gets the value of the numeroLote property.
			 * 
			 */
			public short getNumeroLote() {
				return numeroLote;
			}

			/**
			 * Sets the value of the numeroLote property.
			 * 
			 */
			public void setNumeroLote(short value) {
				this.numeroLote = value;
			}

			/**
			 * Gets the value of the guiasTISS property.
			 * 
			 * @return possible object is
			 *         {@link ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS }
			 * 
			 */
			public ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS getGuiasTISS() {
				return guiasTISS;
			}

			/**
			 * Sets the value of the guiasTISS property.
			 * 
			 * @param value
			 *            allowed object is
			 *            {@link ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS }
			 * 
			 */
			public void setGuiasTISS(
					ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS value) {
				this.guiasTISS = value;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="guiaResumoInternacao" maxOccurs="unbounded" minOccurs="0">
			 *           &lt;complexType>
			 *             &lt;complexContent>
			 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                 &lt;sequence>
			 *                   &lt;element name="numeroGuiaPrestador" type="{http://www.w3.org/2001/XMLSchema}long"/>
			 *                   &lt;element name="numeroGuiaSolicitacaoInternacao" type="{http://www.w3.org/2001/XMLSchema}long"/>
			 *                   &lt;element name="numeroGuiaOperadora" type="{http://www.w3.org/2001/XMLSchema}long"/>
			 *                   &lt;element name="senha" type="{http://www.w3.org/2001/XMLSchema}long"/>
			 *                   &lt;element name="dadosBeneficiario">
			 *                     &lt;complexType>
			 *                       &lt;complexContent>
			 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                           &lt;sequence>
			 *                             &lt;element name="numeroCarteira" type="{http://www.w3.org/2001/XMLSchema}int"/>
			 *                             &lt;element name="atendimentoRN" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                             &lt;element name="nomeBeneficiario" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                           &lt;/sequence>
			 *                         &lt;/restriction>
			 *                       &lt;/complexContent>
			 *                     &lt;/complexType>
			 *                   &lt;/element>
			 *                   &lt;element name="procedimentosExecutados">
			 *                     &lt;complexType>
			 *                       &lt;complexContent>
			 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                           &lt;sequence>
			 *                             &lt;element name="procedimentoExecutado" maxOccurs="unbounded" minOccurs="0">
			 *                               &lt;complexType>
			 *                                 &lt;complexContent>
			 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                                     &lt;choice maxOccurs="unbounded" minOccurs="0">
			 *                                       &lt;element name="dataExecucao" type="{http://www.w3.org/2001/XMLSchema}date"/>
			 *                                       &lt;element name="horaInicial" type="{http://www.w3.org/2001/XMLSchema}time"/>
			 *                                       &lt;element name="horaFinal" type="{http://www.w3.org/2001/XMLSchema}time"/>
			 *                                       &lt;element name="codigoTabela" type="{http://www.w3.org/2001/XMLSchema}byte"/>
			 *                                       &lt;element name="codigoProcedimento" type="{http://www.w3.org/2001/XMLSchema}int"/>
			 *                                       &lt;element name="descricaoProcedimento" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                                       &lt;element name="quantidadeExecutada" type="{http://www.w3.org/2001/XMLSchema}byte"/>
			 *                                       &lt;element name="reducaoAcrescimo" type="{http://www.w3.org/2001/XMLSchema}float"/>
			 *                                       &lt;element name="valorUnitario" type="{http://www.w3.org/2001/XMLSchema}float"/>
			 *                                       &lt;element name="valorTotal" type="{http://www.w3.org/2001/XMLSchema}float"/>
			 *                                       &lt;element name="unidadeMedida" type="{http://www.w3.org/2001/XMLSchema}byte"/>
			 *                                     &lt;/choice>
			 *                                   &lt;/restriction>
			 *                                 &lt;/complexContent>
			 *                               &lt;/complexType>
			 *                             &lt;/element>
			 *                           &lt;/sequence>
			 *                         &lt;/restriction>
			 *                       &lt;/complexContent>
			 *                     &lt;/complexType>
			 *                   &lt;/element>
			 *                   &lt;element name="valorTotal">
			 *                     &lt;complexType>
			 *                       &lt;complexContent>
			 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                           &lt;sequence>
			 *                             &lt;element name="valorProcedimentos" type="{http://www.w3.org/2001/XMLSchema}float"/>
			 *                             &lt;element name="valorDiarias" type="{http://www.w3.org/2001/XMLSchema}float"/>
			 *                             &lt;element name="valorTaxasAlugueis" type="{http://www.w3.org/2001/XMLSchema}float"/>
			 *                             &lt;element name="valorMateriais" type="{http://www.w3.org/2001/XMLSchema}float"/>
			 *                             &lt;element name="valorMedicamentos" type="{http://www.w3.org/2001/XMLSchema}float"/>
			 *                             &lt;element name="valorOPME" type="{http://www.w3.org/2001/XMLSchema}float"/>
			 *                             &lt;element name="valorGasesMedicinais" type="{http://www.w3.org/2001/XMLSchema}float"/>
			 *                             &lt;element name="valorTotalGeral" type="{http://www.w3.org/2001/XMLSchema}float"/>
			 *                           &lt;/sequence>
			 *                         &lt;/restriction>
			 *                       &lt;/complexContent>
			 *                     &lt;/complexType>
			 *                   &lt;/element>
			 *                 &lt;/sequence>
			 *               &lt;/restriction>
			 *             &lt;/complexContent>
			 *           &lt;/complexType>
			 *         &lt;/element>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "guiaResumoInternacao" })
			public static class GuiasTISS {

				protected List<ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS.GuiaResumoInternacao> guiaResumoInternacao;

				/**
				 * Gets the value of the guiaResumoInternacao property.
				 * 
				 * <p>
				 * This accessor method returns a reference to the live list,
				 * not a snapshot. Therefore any modification you make to the
				 * returned list will be present inside the JAXB object. This is
				 * why there is not a <CODE>set</CODE> method for the
				 * guiaResumoInternacao property.
				 * 
				 * <p>
				 * For example, to add a new item, do as follows:
				 * 
				 * <pre>
				 * getGuiaResumoInternacao().add(newItem);
				 * </pre>
				 * 
				 * 
				 * <p>
				 * Objects of the following type(s) are allowed in the list
				 * {@link ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS.GuiaResumoInternacao }
				 * 
				 * 
				 */
				public List<ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS.GuiaResumoInternacao> getGuiaResumoInternacao() {
					if (guiaResumoInternacao == null) {
						guiaResumoInternacao = new ArrayList<ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS.GuiaResumoInternacao>();
					}
					return this.guiaResumoInternacao;
				}

				/**
				 * <p>
				 * Java class for anonymous complex type.
				 * 
				 * <p>
				 * The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * <pre>
				 * &lt;complexType>
				 *   &lt;complexContent>
				 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *       &lt;sequence>
				 *         &lt;element name="numeroGuiaPrestador" type="{http://www.w3.org/2001/XMLSchema}long"/>
				 *         &lt;element name="numeroGuiaSolicitacaoInternacao" type="{http://www.w3.org/2001/XMLSchema}long"/>
				 *         &lt;element name="numeroGuiaOperadora" type="{http://www.w3.org/2001/XMLSchema}long"/>
				 *         &lt;element name="senha" type="{http://www.w3.org/2001/XMLSchema}long"/>
				 *         &lt;element name="dadosBeneficiario">
				 *           &lt;complexType>
				 *             &lt;complexContent>
				 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *                 &lt;sequence>
				 *                   &lt;element name="numeroCarteira" type="{http://www.w3.org/2001/XMLSchema}int"/>
				 *                   &lt;element name="atendimentoRN" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *                   &lt;element name="nomeBeneficiario" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *                 &lt;/sequence>
				 *               &lt;/restriction>
				 *             &lt;/complexContent>
				 *           &lt;/complexType>
				 *         &lt;/element>
				 *         &lt;element name="procedimentosExecutados">
				 *           &lt;complexType>
				 *             &lt;complexContent>
				 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *                 &lt;sequence>
				 *                   &lt;element name="procedimentoExecutado" maxOccurs="unbounded" minOccurs="0">
				 *                     &lt;complexType>
				 *                       &lt;complexContent>
				 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *                           &lt;choice maxOccurs="unbounded" minOccurs="0">
				 *                             &lt;element name="dataExecucao" type="{http://www.w3.org/2001/XMLSchema}date"/>
				 *                             &lt;element name="horaInicial" type="{http://www.w3.org/2001/XMLSchema}time"/>
				 *                             &lt;element name="horaFinal" type="{http://www.w3.org/2001/XMLSchema}time"/>
				 *                             &lt;element name="codigoTabela" type="{http://www.w3.org/2001/XMLSchema}byte"/>
				 *                             &lt;element name="codigoProcedimento" type="{http://www.w3.org/2001/XMLSchema}int"/>
				 *                             &lt;element name="descricaoProcedimento" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *                             &lt;element name="quantidadeExecutada" type="{http://www.w3.org/2001/XMLSchema}byte"/>
				 *                             &lt;element name="reducaoAcrescimo" type="{http://www.w3.org/2001/XMLSchema}float"/>
				 *                             &lt;element name="valorUnitario" type="{http://www.w3.org/2001/XMLSchema}float"/>
				 *                             &lt;element name="valorTotal" type="{http://www.w3.org/2001/XMLSchema}float"/>
				 *                             &lt;element name="unidadeMedida" type="{http://www.w3.org/2001/XMLSchema}byte"/>
				 *                           &lt;/choice>
				 *                         &lt;/restriction>
				 *                       &lt;/complexContent>
				 *                     &lt;/complexType>
				 *                   &lt;/element>
				 *                 &lt;/sequence>
				 *               &lt;/restriction>
				 *             &lt;/complexContent>
				 *           &lt;/complexType>
				 *         &lt;/element>
				 *         &lt;element name="valorTotal">
				 *           &lt;complexType>
				 *             &lt;complexContent>
				 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *                 &lt;sequence>
				 *                   &lt;element name="valorProcedimentos" type="{http://www.w3.org/2001/XMLSchema}float"/>
				 *                   &lt;element name="valorDiarias" type="{http://www.w3.org/2001/XMLSchema}float"/>
				 *                   &lt;element name="valorTaxasAlugueis" type="{http://www.w3.org/2001/XMLSchema}float"/>
				 *                   &lt;element name="valorMateriais" type="{http://www.w3.org/2001/XMLSchema}float"/>
				 *                   &lt;element name="valorMedicamentos" type="{http://www.w3.org/2001/XMLSchema}float"/>
				 *                   &lt;element name="valorOPME" type="{http://www.w3.org/2001/XMLSchema}float"/>
				 *                   &lt;element name="valorGasesMedicinais" type="{http://www.w3.org/2001/XMLSchema}float"/>
				 *                   &lt;element name="valorTotalGeral" type="{http://www.w3.org/2001/XMLSchema}float"/>
				 *                 &lt;/sequence>
				 *               &lt;/restriction>
				 *             &lt;/complexContent>
				 *           &lt;/complexType>
				 *         &lt;/element>
				 *       &lt;/sequence>
				 *     &lt;/restriction>
				 *   &lt;/complexContent>
				 * &lt;/complexType>
				 * </pre>
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "", propOrder = { "numeroGuiaPrestador",
						"numeroGuiaSolicitacaoInternacao",
						"numeroGuiaOperadora", "senha", "dadosBeneficiario",
						"procedimentosExecutados", "valorTotal" })
				public static class GuiaResumoInternacao {

					protected long numeroGuiaPrestador;
					protected long numeroGuiaSolicitacaoInternacao;
					protected long numeroGuiaOperadora;
					protected long senha;
					@XmlElement(required = true)
					protected ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS.GuiaResumoInternacao.DadosBeneficiario dadosBeneficiario;
					@XmlElement(required = true)
					protected ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS.GuiaResumoInternacao.ProcedimentosExecutados procedimentosExecutados;
					@XmlElement(required = true)
					protected ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS.GuiaResumoInternacao.ValorTotal valorTotal;

					/**
					 * Gets the value of the numeroGuiaPrestador property.
					 * 
					 */
					public long getNumeroGuiaPrestador() {
						return numeroGuiaPrestador;
					}

					/**
					 * Sets the value of the numeroGuiaPrestador property.
					 * 
					 */
					public void setNumeroGuiaPrestador(long value) {
						this.numeroGuiaPrestador = value;
					}

					/**
					 * Gets the value of the numeroGuiaSolicitacaoInternacao
					 * property.
					 * 
					 */
					public long getNumeroGuiaSolicitacaoInternacao() {
						return numeroGuiaSolicitacaoInternacao;
					}

					/**
					 * Sets the value of the numeroGuiaSolicitacaoInternacao
					 * property.
					 * 
					 */
					public void setNumeroGuiaSolicitacaoInternacao(long value) {
						this.numeroGuiaSolicitacaoInternacao = value;
					}

					/**
					 * Gets the value of the numeroGuiaOperadora property.
					 * 
					 */
					public long getNumeroGuiaOperadora() {
						return numeroGuiaOperadora;
					}

					/**
					 * Sets the value of the numeroGuiaOperadora property.
					 * 
					 */
					public void setNumeroGuiaOperadora(long value) {
						this.numeroGuiaOperadora = value;
					}

					/**
					 * Gets the value of the senha property.
					 * 
					 */
					public long getSenha() {
						return senha;
					}

					/**
					 * Sets the value of the senha property.
					 * 
					 */
					public void setSenha(long value) {
						this.senha = value;
					}

					/**
					 * Gets the value of the dadosBeneficiario property.
					 * 
					 * @return possible object is
					 *         {@link ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS.GuiaResumoInternacao.DadosBeneficiario }
					 * 
					 */
					public ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS.GuiaResumoInternacao.DadosBeneficiario getDadosBeneficiario() {
						return dadosBeneficiario;
					}

					/**
					 * Sets the value of the dadosBeneficiario property.
					 * 
					 * @param value
					 *            allowed object is
					 *            {@link ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS.GuiaResumoInternacao.DadosBeneficiario }
					 * 
					 */
					public void setDadosBeneficiario(
							ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS.GuiaResumoInternacao.DadosBeneficiario value) {
						this.dadosBeneficiario = value;
					}

					/**
					 * Gets the value of the procedimentosExecutados property.
					 * 
					 * @return possible object is
					 *         {@link ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS.GuiaResumoInternacao.ProcedimentosExecutados }
					 * 
					 */
					public ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS.GuiaResumoInternacao.ProcedimentosExecutados getProcedimentosExecutados() {
						return procedimentosExecutados;
					}

					/**
					 * Sets the value of the procedimentosExecutados property.
					 * 
					 * @param value
					 *            allowed object is
					 *            {@link ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS.GuiaResumoInternacao.ProcedimentosExecutados }
					 * 
					 */
					public void setProcedimentosExecutados(
							ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS.GuiaResumoInternacao.ProcedimentosExecutados value) {
						this.procedimentosExecutados = value;
					}

					/**
					 * Gets the value of the valorTotal property.
					 * 
					 * @return possible object is
					 *         {@link ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS.GuiaResumoInternacao.ValorTotal }
					 * 
					 */
					public ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS.GuiaResumoInternacao.ValorTotal getValorTotal() {
						return valorTotal;
					}

					/**
					 * Sets the value of the valorTotal property.
					 * 
					 * @param value
					 *            allowed object is
					 *            {@link ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS.GuiaResumoInternacao.ValorTotal }
					 * 
					 */
					public void setValorTotal(
							ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS.GuiaResumoInternacao.ValorTotal value) {
						this.valorTotal = value;
					}

					/**
					 * <p>
					 * Java class for anonymous complex type.
					 * 
					 * <p>
					 * The following schema fragment specifies the expected
					 * content contained within this class.
					 * 
					 * <pre>
					 * &lt;complexType>
					 *   &lt;complexContent>
					 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
					 *       &lt;sequence>
					 *         &lt;element name="numeroCarteira" type="{http://www.w3.org/2001/XMLSchema}int"/>
					 *         &lt;element name="atendimentoRN" type="{http://www.w3.org/2001/XMLSchema}string"/>
					 *         &lt;element name="nomeBeneficiario" type="{http://www.w3.org/2001/XMLSchema}string"/>
					 *       &lt;/sequence>
					 *     &lt;/restriction>
					 *   &lt;/complexContent>
					 * &lt;/complexType>
					 * </pre>
					 * 
					 * 
					 */
					@XmlAccessorType(XmlAccessType.FIELD)
					@XmlType(name = "", propOrder = { "numeroCarteira",
							"atendimentoRN", "nomeBeneficiario" })
					public static class DadosBeneficiario {

						protected int numeroCarteira;
						@XmlElement(required = true)
						protected String atendimentoRN;
						@XmlElement(required = true)
						protected String nomeBeneficiario;

						/**
						 * Gets the value of the numeroCarteira property.
						 * 
						 */
						public int getNumeroCarteira() {
							return numeroCarteira;
						}

						/**
						 * Sets the value of the numeroCarteira property.
						 * 
						 */
						public void setNumeroCarteira(int value) {
							this.numeroCarteira = value;
						}

						/**
						 * Gets the value of the atendimentoRN property.
						 * 
						 * @return possible object is {@link String }
						 * 
						 */
						public String getAtendimentoRN() {
							return atendimentoRN;
						}

						/**
						 * Sets the value of the atendimentoRN property.
						 * 
						 * @param value
						 *            allowed object is {@link String }
						 * 
						 */
						public void setAtendimentoRN(String value) {
							this.atendimentoRN = value;
						}

						/**
						 * Gets the value of the nomeBeneficiario property.
						 * 
						 * @return possible object is {@link String }
						 * 
						 */
						public String getNomeBeneficiario() {
							return nomeBeneficiario;
						}

						/**
						 * Sets the value of the nomeBeneficiario property.
						 * 
						 * @param value
						 *            allowed object is {@link String }
						 * 
						 */
						public void setNomeBeneficiario(String value) {
							this.nomeBeneficiario = value;
						}

					}

					/**
					 * <p>
					 * Java class for anonymous complex type.
					 * 
					 * <p>
					 * The following schema fragment specifies the expected
					 * content contained within this class.
					 * 
					 * <pre>
					 * &lt;complexType>
					 *   &lt;complexContent>
					 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
					 *       &lt;sequence>
					 *         &lt;element name="procedimentoExecutado" maxOccurs="unbounded" minOccurs="0">
					 *           &lt;complexType>
					 *             &lt;complexContent>
					 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
					 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
					 *                   &lt;element name="dataExecucao" type="{http://www.w3.org/2001/XMLSchema}date"/>
					 *                   &lt;element name="horaInicial" type="{http://www.w3.org/2001/XMLSchema}time"/>
					 *                   &lt;element name="horaFinal" type="{http://www.w3.org/2001/XMLSchema}time"/>
					 *                   &lt;element name="codigoTabela" type="{http://www.w3.org/2001/XMLSchema}byte"/>
					 *                   &lt;element name="codigoProcedimento" type="{http://www.w3.org/2001/XMLSchema}int"/>
					 *                   &lt;element name="descricaoProcedimento" type="{http://www.w3.org/2001/XMLSchema}string"/>
					 *                   &lt;element name="quantidadeExecutada" type="{http://www.w3.org/2001/XMLSchema}byte"/>
					 *                   &lt;element name="reducaoAcrescimo" type="{http://www.w3.org/2001/XMLSchema}float"/>
					 *                   &lt;element name="valorUnitario" type="{http://www.w3.org/2001/XMLSchema}float"/>
					 *                   &lt;element name="valorTotal" type="{http://www.w3.org/2001/XMLSchema}float"/>
					 *                   &lt;element name="unidadeMedida" type="{http://www.w3.org/2001/XMLSchema}byte"/>
					 *                 &lt;/choice>
					 *               &lt;/restriction>
					 *             &lt;/complexContent>
					 *           &lt;/complexType>
					 *         &lt;/element>
					 *       &lt;/sequence>
					 *     &lt;/restriction>
					 *   &lt;/complexContent>
					 * &lt;/complexType>
					 * </pre>
					 * 
					 * 
					 */
					@XmlAccessorType(XmlAccessType.FIELD)
					@XmlType(name = "", propOrder = { "procedimentoExecutado" })
					public static class ProcedimentosExecutados {

						protected List<ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS.GuiaResumoInternacao.ProcedimentosExecutados.ProcedimentoExecutado> procedimentoExecutado;

						/**
						 * Gets the value of the procedimentoExecutado property.
						 * 
						 * <p>
						 * This accessor method returns a reference to the live
						 * list, not a snapshot. Therefore any modification you
						 * make to the returned list will be present inside the
						 * JAXB object. This is why there is not a
						 * <CODE>set</CODE> method for the procedimentoExecutado
						 * property.
						 * 
						 * <p>
						 * For example, to add a new item, do as follows:
						 * 
						 * <pre>
						 * getProcedimentoExecutado().add(newItem);
						 * </pre>
						 * 
						 * 
						 * <p>
						 * Objects of the following type(s) are allowed in the
						 * list
						 * {@link ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS.GuiaResumoInternacao.ProcedimentosExecutados.ProcedimentoExecutado }
						 * 
						 * 
						 */
						public List<ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS.GuiaResumoInternacao.ProcedimentosExecutados.ProcedimentoExecutado> getProcedimentoExecutado() {
							if (procedimentoExecutado == null) {
								procedimentoExecutado = new ArrayList<ContainerDadosSantaHelenaXML.PrestadorParaOperadora.LoteGuias.GuiasTISS.GuiaResumoInternacao.ProcedimentosExecutados.ProcedimentoExecutado>();
							}
							return this.procedimentoExecutado;
						}

						/**
						 * <p>
						 * Java class for anonymous complex type.
						 * 
						 * <p>
						 * The following schema fragment specifies the expected
						 * content contained within this class.
						 * 
						 * <pre>
						 * &lt;complexType>
						 *   &lt;complexContent>
						 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
						 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
						 *         &lt;element name="dataExecucao" type="{http://www.w3.org/2001/XMLSchema}date"/>
						 *         &lt;element name="horaInicial" type="{http://www.w3.org/2001/XMLSchema}time"/>
						 *         &lt;element name="horaFinal" type="{http://www.w3.org/2001/XMLSchema}time"/>
						 *         &lt;element name="codigoTabela" type="{http://www.w3.org/2001/XMLSchema}byte"/>
						 *         &lt;element name="codigoProcedimento" type="{http://www.w3.org/2001/XMLSchema}int"/>
						 *         &lt;element name="descricaoProcedimento" type="{http://www.w3.org/2001/XMLSchema}string"/>
						 *         &lt;element name="quantidadeExecutada" type="{http://www.w3.org/2001/XMLSchema}byte"/>
						 *         &lt;element name="reducaoAcrescimo" type="{http://www.w3.org/2001/XMLSchema}float"/>
						 *         &lt;element name="valorUnitario" type="{http://www.w3.org/2001/XMLSchema}float"/>
						 *         &lt;element name="valorTotal" type="{http://www.w3.org/2001/XMLSchema}float"/>
						 *         &lt;element name="unidadeMedida" type="{http://www.w3.org/2001/XMLSchema}byte"/>
						 *       &lt;/choice>
						 *     &lt;/restriction>
						 *   &lt;/complexContent>
						 * &lt;/complexType>
						 * </pre>
						 * 
						 * 
						 */
						@XmlAccessorType(XmlAccessType.FIELD)
						@XmlType(name = "", propOrder = { "dataExecucaoOrHoraInicialOrHoraFinal" })
						public static class ProcedimentoExecutado {

							@XmlElementRefs({
									@XmlElementRef(name = "valorTotal", namespace = "http://www.ans.gov.br/padroes/tiss/schemas", type = JAXBElement.class, required = false),
									@XmlElementRef(name = "codigoProcedimento", namespace = "http://www.ans.gov.br/padroes/tiss/schemas", type = JAXBElement.class, required = false),
									@XmlElementRef(name = "quantidadeExecutada", namespace = "http://www.ans.gov.br/padroes/tiss/schemas", type = JAXBElement.class, required = false),
									@XmlElementRef(name = "codigoTabela", namespace = "http://www.ans.gov.br/padroes/tiss/schemas", type = JAXBElement.class, required = false),
									@XmlElementRef(name = "horaFinal", namespace = "http://www.ans.gov.br/padroes/tiss/schemas", type = JAXBElement.class, required = false),
									@XmlElementRef(name = "unidadeMedida", namespace = "http://www.ans.gov.br/padroes/tiss/schemas", type = JAXBElement.class, required = false),
									@XmlElementRef(name = "dataExecucao", namespace = "http://www.ans.gov.br/padroes/tiss/schemas", type = JAXBElement.class, required = false),
									@XmlElementRef(name = "horaInicial", namespace = "http://www.ans.gov.br/padroes/tiss/schemas", type = JAXBElement.class, required = false),
									@XmlElementRef(name = "descricaoProcedimento", namespace = "http://www.ans.gov.br/padroes/tiss/schemas", type = JAXBElement.class, required = false),
									@XmlElementRef(name = "valorUnitario", namespace = "http://www.ans.gov.br/padroes/tiss/schemas", type = JAXBElement.class, required = false),
									@XmlElementRef(name = "reducaoAcrescimo", namespace = "http://www.ans.gov.br/padroes/tiss/schemas", type = JAXBElement.class, required = false) })
							protected List<JAXBElement<?>> dataExecucaoOrHoraInicialOrHoraFinal;

							/**
							 * Gets the value of the
							 * dataExecucaoOrHoraInicialOrHoraFinal property.
							 * 
							 * <p>
							 * This accessor method returns a reference to the
							 * live list, not a snapshot. Therefore any
							 * modification you make to the returned list will
							 * be present inside the JAXB object. This is why
							 * there is not a <CODE>set</CODE> method for the
							 * dataExecucaoOrHoraInicialOrHoraFinal property.
							 * 
							 * <p>
							 * For example, to add a new item, do as follows:
							 * 
							 * <pre>
							 * getDataExecucaoOrHoraInicialOrHoraFinal().add(newItem);
							 * </pre>
							 * 
							 * 
							 * <p>
							 * Objects of the following type(s) are allowed in
							 * the list {@link JAXBElement }{@code <}
							 * {@link Float }{@code >} {@link JAXBElement }
							 * {@code <}{@link Integer }{@code >}
							 * {@link JAXBElement }{@code <}{@link Byte }{@code >}
							 * {@link JAXBElement }{@code <}
							 * {@link XMLGregorianCalendar }{@code >}
							 * {@link JAXBElement }{@code <}{@link Byte }{@code >}
							 * {@link JAXBElement }{@code <}
							 * {@link XMLGregorianCalendar }{@code >}
							 * {@link JAXBElement }{@code <}{@link Byte }{@code >}
							 * {@link JAXBElement }{@code <}
							 * {@link XMLGregorianCalendar }{@code >}
							 * {@link JAXBElement }{@code <}{@link String }
							 * {@code >} {@link JAXBElement }{@code <}
							 * {@link Float }{@code >} {@link JAXBElement }
							 * {@code <}{@link Float }{@code >}
							 * 
							 * 
							 */
							public List<JAXBElement<?>> getDataExecucaoOrHoraInicialOrHoraFinal() {
								if (dataExecucaoOrHoraInicialOrHoraFinal == null) {
									dataExecucaoOrHoraInicialOrHoraFinal = new ArrayList<JAXBElement<?>>();
								}
								return this.dataExecucaoOrHoraInicialOrHoraFinal;
							}

						}

					}

					/**
					 * <p>
					 * Java class for anonymous complex type.
					 * 
					 * <p>
					 * The following schema fragment specifies the expected
					 * content contained within this class.
					 * 
					 * <pre>
					 * &lt;complexType>
					 *   &lt;complexContent>
					 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
					 *       &lt;sequence>
					 *         &lt;element name="valorProcedimentos" type="{http://www.w3.org/2001/XMLSchema}float"/>
					 *         &lt;element name="valorDiarias" type="{http://www.w3.org/2001/XMLSchema}float"/>
					 *         &lt;element name="valorTaxasAlugueis" type="{http://www.w3.org/2001/XMLSchema}float"/>
					 *         &lt;element name="valorMateriais" type="{http://www.w3.org/2001/XMLSchema}float"/>
					 *         &lt;element name="valorMedicamentos" type="{http://www.w3.org/2001/XMLSchema}float"/>
					 *         &lt;element name="valorOPME" type="{http://www.w3.org/2001/XMLSchema}float"/>
					 *         &lt;element name="valorGasesMedicinais" type="{http://www.w3.org/2001/XMLSchema}float"/>
					 *         &lt;element name="valorTotalGeral" type="{http://www.w3.org/2001/XMLSchema}float"/>
					 *       &lt;/sequence>
					 *     &lt;/restriction>
					 *   &lt;/complexContent>
					 * &lt;/complexType>
					 * </pre>
					 * 
					 * 
					 */
					@XmlAccessorType(XmlAccessType.FIELD)
					@XmlType(name = "", propOrder = { "valorProcedimentos",
							"valorDiarias", "valorTaxasAlugueis",
							"valorMateriais", "valorMedicamentos", "valorOPME",
							"valorGasesMedicinais", "valorTotalGeral" })
					public static class ValorTotal {

						protected float valorProcedimentos;
						protected float valorDiarias;
						protected float valorTaxasAlugueis;
						protected float valorMateriais;
						protected float valorMedicamentos;
						protected float valorOPME;
						protected float valorGasesMedicinais;
						protected float valorTotalGeral;

						/**
						 * Gets the value of the valorProcedimentos property.
						 * 
						 */
						public float getValorProcedimentos() {
							return valorProcedimentos;
						}

						/**
						 * Sets the value of the valorProcedimentos property.
						 * 
						 */
						public void setValorProcedimentos(float value) {
							this.valorProcedimentos = value;
						}

						/**
						 * Gets the value of the valorDiarias property.
						 * 
						 */
						public float getValorDiarias() {
							return valorDiarias;
						}

						/**
						 * Sets the value of the valorDiarias property.
						 * 
						 */
						public void setValorDiarias(float value) {
							this.valorDiarias = value;
						}

						/**
						 * Gets the value of the valorTaxasAlugueis property.
						 * 
						 */
						public float getValorTaxasAlugueis() {
							return valorTaxasAlugueis;
						}

						/**
						 * Sets the value of the valorTaxasAlugueis property.
						 * 
						 */
						public void setValorTaxasAlugueis(float value) {
							this.valorTaxasAlugueis = value;
						}

						/**
						 * Gets the value of the valorMateriais property.
						 * 
						 */
						public float getValorMateriais() {
							return valorMateriais;
						}

						/**
						 * Sets the value of the valorMateriais property.
						 * 
						 */
						public void setValorMateriais(float value) {
							this.valorMateriais = value;
						}

						/**
						 * Gets the value of the valorMedicamentos property.
						 * 
						 */
						public float getValorMedicamentos() {
							return valorMedicamentos;
						}

						/**
						 * Sets the value of the valorMedicamentos property.
						 * 
						 */
						public void setValorMedicamentos(float value) {
							this.valorMedicamentos = value;
						}

						/**
						 * Gets the value of the valorOPME property.
						 * 
						 */
						public float getValorOPME() {
							return valorOPME;
						}

						/**
						 * Sets the value of the valorOPME property.
						 * 
						 */
						public void setValorOPME(float value) {
							this.valorOPME = value;
						}

						/**
						 * Gets the value of the valorGasesMedicinais property.
						 * 
						 */
						public float getValorGasesMedicinais() {
							return valorGasesMedicinais;
						}

						/**
						 * Sets the value of the valorGasesMedicinais property.
						 * 
						 */
						public void setValorGasesMedicinais(float value) {
							this.valorGasesMedicinais = value;
						}

						/**
						 * Gets the value of the valorTotalGeral property.
						 * 
						 */
						public float getValorTotalGeral() {
							return valorTotalGeral;
						}

						/**
						 * Sets the value of the valorTotalGeral property.
						 * 
						 */
						public void setValorTotalGeral(float value) {
							this.valorTotalGeral = value;
						}

					}

				}

			}

		}

	}


	
	public JAXBElement<?> getFieldFromListJaxbElementsByName(List<JAXBElement<?>> list, String nome) {
		for (JAXBElement<?> jaxbElement : list) {
			if(jaxbElement.getName().getLocalPart().toString().equals(nome)) {
				return jaxbElement;
			}
		}
		
		return null;

	}

}
