//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.16 at 01:00:50 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ans.gov.br/padroes/tiss/schemas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.com.glosma.associacao.faturas.hospital.santahelena;
