//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.16 at 01:00:50 PM BRT 
//

package br.com.glosma.associacao.faturas.convenio.glosamaxx;

import java.util.ArrayList;
import java.util.List;

import br.com.glosma.associacao.core.interfaces.convenio.IProcedimentoExecutadoCovenio;
import br.com.glosma.associacao.faturas.commons.infra.csv.CSV;
import br.com.glosma.associacao.faturas.commons.infra.csv.FieldCSV;
import br.com.glosma.associacao.faturas.commons.infra.csv.ListCSV;

@CSV
public class ContainerDadosGlosaMaxxCSV {

	@ListCSV(indexLineStart = 5)
	private List<ProcedimentoGlosaMaxxCSV> procedimentos;

	public ContainerDadosGlosaMaxxCSV() {
		procedimentos = new ArrayList<ProcedimentoGlosaMaxxCSV>();

	}
	
	@CSV
	public static class ProcedimentoGlosaMaxxCSV implements IProcedimentoExecutadoCovenio{
		@FieldCSV(indexColumn = 10, isDadoNaLinhaAtual=true)
		private String beneficiario;
		@FieldCSV(indexColumn = 14, isDadoNaLinhaAtual=true)
		private String descricao;
		@FieldCSV(indexColumn = 23, isDadoNaLinhaAtual=true)
		private String descricaoGlosa;
		@FieldCSV(indexColumn = 21, isDadoNaLinhaAtual=true)
		private String valorGlosa;
		@FieldCSV(indexColumn = 20, isDadoNaLinhaAtual=true)
		private String valorLiberado;
		@FieldCSV(indexColumn = 19, isDadoNaLinhaAtual=true)
		private String valorInformado;
		@FieldCSV(indexColumn = 18, isDadoNaLinhaAtual=true)
		private String quantidadeExecutada;
		@FieldCSV(indexColumn = 13, isDadoNaLinhaAtual=true)
		private String codigoServico;
		@FieldCSV(indexColumn = 11, isDadoNaLinhaAtual=true)
		private String dataRealizacao;

		public String getBeneficiario() {
			return beneficiario;
		}

		public void setBeneficiario(String beneficiario) {
			this.beneficiario = beneficiario;
		}

		public String getDescricao() {
			return descricao;
		}

		public void setDescricao(String descricao) {
			this.descricao = descricao;
		}

		public String getDescricaoGlosa() {
			return descricaoGlosa;
		}

		public void setDescricaoGlosa(String descricaoGlosa) {
			this.descricaoGlosa = descricaoGlosa;
		}

		public String getValorGlosa() {
			return valorGlosa;
		}

		public void setValorGlosa(String valorGlosa) {
			this.valorGlosa = valorGlosa;
		}

		public String getValorLiberado() {
			return valorLiberado;
		}

		public void setValorLiberado(String valorLiberado) {
			this.valorLiberado = valorLiberado;
		}

		public String getValorInformado() {
			return valorInformado;
		}

		public void setValorInformado(String valorInformado) {
			this.valorInformado = valorInformado;
		}

		public String getQuantidadeExecutada() {
			return quantidadeExecutada;
		}

		public void setQuantidadeExecutada(String quantidadeExecutada) {
			this.quantidadeExecutada = quantidadeExecutada;
		}

		public String getCodigoServico() {
			return codigoServico;
		}

		public void setCodigoServico(String codigoServico) {
			this.codigoServico = codigoServico;
		}

		public String getDataRealizacao() {
			return dataRealizacao;
		}

		public void setDataRealizacao(String dataRealizacao) {
			this.dataRealizacao = dataRealizacao;
		}

	}

	public List<ProcedimentoGlosaMaxxCSV> getProcedimentos() {
		return procedimentos;
	}

	public void setProcedimentos(List<ProcedimentoGlosaMaxxCSV> procedimentos) {
		this.procedimentos = procedimentos;
	}
	
	
}
